package app.simple.felicity.repository.maps

import androidx.annotation.DrawableRes
import app.simple.felicity.repository.R

object GenreMap {

    private val commonImage = R.drawable.common

    val genreGroupImages = mapOf(
            "Pop" to R.drawable.pop,
            "Rock" to R.drawable.rock,
            "Hip-Hop_Rap" to R.drawable.hiphop,
            "R&B" to R.drawable.rnb,
            "Reggae" to R.drawable.reggae,
            "Country" to R.drawable.country,
            "Folk" to R.drawable.folk,
            "Jazz" to R.drawable.jazz,
            "Classical" to R.drawable.classical,
            "Blues" to R.drawable.blues,
            "Electronic" to R.drawable.electronic,
            "Children" to R.drawable.children,
            "Christian" to R.drawable.christian,
            "Latino" to R.drawable.latino,
            "Alternative" to R.drawable.alternative,
            "NewAge" to R.drawable.newage,
            "Anime" to R.drawable.anime,
            "Urdu" to R.drawable.urdu,
            "Indian" to R.drawable.indian,
            "Dance" to R.drawable.dance,
            "Vocal" to R.drawable.vocal,
    )

    val genreToGroup = mapOf(
            // Pop and sub-genres
            "Pop" to "Pop",
            "Baroque Pop" to "Pop",
            "Country Pop" to "Pop",
            "Contemporary R&B" to "Pop",
            "Cowboy Pop" to "Pop",
            "Dancehall Pop" to "Pop",
            "Electropop" to "Pop",
            "Emo Pop" to "Pop",
            "Folk-Pop" to "Pop",
            "Hip-Pop" to "Pop",
            "Indie Pop" to "Pop",
            "Pop Punk" to "Pop",
            "Pop Rap" to "Pop",
            "Ambient Pop" to "Pop",
            "Pop Rock" to "Pop",
            "Power Pop" to "Pop",
            "Psychedelic Pop" to "Pop",
            "Space Age Pop" to "Pop",
            "Worldbeat" to "Pop",
            "Synthpop" to "Pop",
            "World" to "Pop",
            "K-Pop" to "Pop",
            "J-Pop" to "Pop",
            "Поп" to "Pop",
            "Mandopop" to "Pop",

            // Rock and sub-genres
            "Rock" to "Rock",
            "Adult Alternative" to "Rock",
            "American Rock" to "Rock",
            "Arena Rock" to "Rock",
            "Blues-Rock" to "Rock",
            "British Invasion" to "Rock",
            "Death Metal" to "Rock",
            "Black Metal" to "Rock",
            "Glam Rock" to "Rock",
            "Hair Metal" to "Rock",
            "Hard Rock" to "Rock",
            "Metal" to "Rock",
            "Jam Bands" to "Rock",
            "Prog-Rock" to "Rock",
            "Art Rock" to "Rock",
            "Psychedelic" to "Rock",
            "Rock & Roll" to "Rock",
            "Rockabilly" to "Rock",
            "Roots Rock" to "Rock",
            "Singer/Songwriter" to "Rock",
            "Classic Rock" to "Rock",
            "Southern Rock" to "Rock",
            "Punk" to "Rock",
            "Grunge" to "Rock",
            "Indie Rock" to "Rock",
            "Alternative Rock" to "Rock",
            "Experimental Rock" to "Rock",
            "Goth Rock" to "Rock",
            "Hardcore Punk" to "Rock",
            "New Wave" to "Rock",
            "Progressive Rock" to "Rock",
            "Shoegaze" to "Rock",
            "Steampunk" to "Rock",
            "Pop & Rock" to "Rock",

            // Hip-Hop/Rap and sub-genres
            "Hip-Hop" to "Hip-Hop_Rap",
            "Rap" to "Hip-Hop_Rap",
            "Alternative Rap" to "Hip-Hop_Rap",
            "Bounce" to "Hip-Hop_Rap",
            "Dirty South" to "Hip-Hop_Rap",
            "East Coast Rap" to "Hip-Hop_Rap",
            "Gangsta Rap" to "Hip-Hop_Rap",
            "Hardcore Rap" to "Hip-Hop_Rap",
            "Latin Rap" to "Hip-Hop_Rap",
            "Old School Rap" to "Hip-Hop_Rap",
            "Underground Rap" to "Hip-Hop_Rap",
            "West Coast Rap" to "Hip-Hop_Rap",
            "Mumble Rap" to "Hip-Hop_Rap",

            // R&B and sub-genres
            "R&B" to "R&B",
            "Contemporary R&B" to "R&B",
            "Disco" to "R&B",
            "Doo Wop" to "R&B",
            "Funk" to "R&B",
            "Motown" to "R&B",
            "Neo-Soul" to "R&B",
            "Quiet Storm" to "R&B",
            "Soul" to "R&B",

            // Reggae and sub-genres
            "Reggae" to "Reggae",
            "Dancehall" to "Reggae",
            "Dub" to "Reggae",
            "Roots Reggae" to "Reggae",
            "Ska" to "Reggae",
            "Mento" to "Reggae",
            "Reggaestep" to "Reggae",
            "Gospel Reggae" to "Reggae",
            "Contemporary Reggae" to "Reggae",

            // Country and sub-genres
            "Country" to "Country",
            "Alternative Country" to "Country",
            "Americana" to "Country",
            "Bluegrass" to "Country",
            "Contemporary Bluegrass" to "Country",
            "Contemporary Country" to "Country",
            "Country Gospel" to "Country",
            "Honky Tonk" to "Country",
            "Outlaw Country" to "Country",
            "Traditional Bluegrass" to "Country",
            "Traditional Country" to "Country",
            "Urban Cowboy" to "Country",
            "Country and Pop" to "Country",

            // Folk and sub-genres
            "Folk" to "Folk",
            "Folk Metal" to "Folk",
            "Folk Rock" to "Folk",
            "Neo-Folk" to "Folk",
            "Anti-folk" to "Folk",
            "Indie Folk" to "Folk",
            "Folk Punk" to "Folk",
            "Contemporary Folk" to "Folk",
            "Progressive Folk" to "Folk",
            "Folk Country" to "Folk",
            "Psychedelic Folk" to "Folk",
            "Americana" to "Folk",
            "Skiffle" to "Folk",
            "Ballads" to "Folk",

            // Jazz and sub-genres
            "Jazz" to "Jazz",
            "Acid Jazz" to "Jazz",
            "Avant-Garde Jazz" to "Jazz",
            "Big Band" to "Jazz",
            "Blue Note" to "Jazz",
            "Contemporary Jazz" to "Jazz",
            "Easy Listening" to "Jazz",
            "Crossover Jazz" to "Jazz",
            "Dixieland" to "Jazz",
            "Ethio-Jazz Fusion" to "Jazz",
            "Hard Bop" to "Jazz",
            "Latin Jazz" to "Jazz",
            "Mainstream Jazz" to "Jazz",
            "Ragtime" to "Jazz",
            "Smooth Jazz" to "Jazz",
            "Trad Jazz" to "Jazz",

            // Classical and sub-genres
            "Classical" to "Classical",
            "Avant-Garde" to "Classical",
            "Baroque" to "Classical",
            "Chamber Music" to "Classical",
            "Chant" to "Classical",
            "Choral" to "Classical",
            "Classical Crossover" to "Classical",
            "Early Music" to "Classical",
            "High Classical" to "Classical",
            "Impressionist" to "Classical",
            "Medieval" to "Classical",
            "Minimalism" to "Classical",
            "Modern Composition" to "Classical",
            "Opera" to "Classical",
            "Orchestral" to "Classical",
            "Renaissance" to "Classical",
            "Romantic" to "Classical",
            "Wedding Music" to "Classical",

            // Blues and sub-genres
            "Blues" to "Blues",
            "Acoustic Blues" to "Blues",
            "Chicago Blues" to "Blues",
            "Classic Blues" to "Blues",
            "Contemporary Blues" to "Blues",
            "Country Blues" to "Blues",
            "Delta Blues" to "Blues",
            "Electric Blues" to "Blues",

            // Electronic and sub-genres
            "Electronic" to "Electronic",
            "Electronica" to "Electronic",
            "Breakbeat" to "Electronic",
            "Dubstep" to "Electronic",
            "Exercise" to "Electronic",
            "Garage" to "Electronic",
            "Hardcore" to "Electronic",
            "Hard Dance" to "Electronic",
            "Hi-NRG" to "Electronic",
            "Eurodance" to "Electronic",
            "House" to "Electronic",
            "Jackin House" to "Electronic",
            "Jungle" to "Electronic",
            "Drum N Bass" to "Electronic",
            "Techno" to "Electronic",
            "Trance" to "Electronic",
            "Jungle/Drum'n'bass" to "Electronic",
            "Downtempo" to "Electronic",

            // Children's Music and sub-genres
            "Children's Music" to "Children",
            "Lullabies" to "Children",
            "Sing-Along" to "Children",
            "Stories" to "Children",

            // Christian and sub-genres
            "Christian" to "Christian",
            "CCM" to "Christian",
            "Christian Metal" to "Christian",
            "Christian Pop" to "Christian",
            "Christian Rap" to "Christian",
            "Christian Rock" to "Christian",
            "Classic Christian" to "Christian",
            "Contemporary Gospel" to "Christian",
            "Gospel" to "Christian",
            "Christian & Gospel" to "Christian",
            "Praise & Worship" to "Christian",
            "Qawwali" to "Christian",
            "Southern Gospel" to "Christian",
            "Traditional Gospel" to "Christian",

            // Latino and sub-genres
            "Latin" to "Latino",
            "Latino" to "Latino",
            "Alternativo & Rock Latino" to "Latino",
            "Baladas y Boleros" to "Latino",
            "Brazilian" to "Latino",
            "Contemporary Latin" to "Latino",
            "Latin Jazz" to "Latino",
            "Pop Latino" to "Latino",
            "Raíces" to "Latino",
            "Reggaeton y Hip-Hop" to "Latino",
            "Regional Mexicano" to "Latino",
            "Salsa" to "Latino",
            "Tropical" to "Latino",
            "Bachata" to "Latino",
            "Rumba" to "Latino",
            "Tango" to "Latino",
            "Vallenato" to "Latino",
            "Urban Latino" to "Latino",
            "Pop in Spanish" to "Latino",
            "Latin Pop" to "Latino",
            "Latin Rap" to "Latino",

            // Alternative and sub-genres
            "Alternative" to "Alternative",
            "Alternative Rock" to "Alternative",
            "College Rock" to "Alternative",
            "Experimental Rock" to "Alternative",
            "Goth Rock" to "Alternative",
            "Grunge" to "Alternative",
            "Hardcore Punk" to "Alternative",
            "Hard Rock" to "Alternative",
            "Indie Rock" to "Alternative",
            "New Wave" to "Alternative",
            "Progressive Rock" to "Alternative",
            "Punk" to "Alternative",
            "Shoegaze" to "Alternative",
            "Steampunk" to "Alternative",
            "Альтернатива" to "Alternative",

            // New Age and sub-genres
            "New Age" to "NewAge",
            "Environmental" to "NewAge",
            "Healing" to "NewAge",
            "Meditation" to "NewAge",
            "Nature" to "NewAge",
            "Relaxation" to "NewAge",
            "Travel" to "NewAge",

            // Anime and sub-genres
            "Anime" to "Anime",
            "Anime Music" to "Anime",
            "Anime Soundtracks" to "Anime",

            // Urdu
            "Urdu" to "Urdu",
            "Urdu Pop" to "Urdu",
            "Urdu Ghazal" to "Urdu",
            "Ghazal" to "Urdu",
            "Qawwali" to "Urdu",
            "Ghazals" to "Urdu",
            "Urdu Classical" to "Urdu",
            "Urdu Folk" to "Urdu",

            // Indian
            "Indian" to "Indian",
            "Hindi" to "Indian",
            "Telugu" to "Indian",
            "Tamil" to "Indian",
            "Punjabi" to "Indian",
            "Bhangra" to "Indian",
            "Bollywood" to "Indian",
            "Indian Classical" to "Indian",
            "Indian Folk" to "Indian",
            "Indian Pop" to "Indian",
            "Bhojpuri" to "Indian",
            "Kannada" to "Indian",
            "Панджаби-поп" to "Indian",

            // Dance
            "Dance" to "Dance",
            "Dance-Pop" to "Dance",
            "EDM" to "Dance",
            "House" to "Dance",
            "Trance" to "Dance",
            "Techno" to "Dance",
            "Electro" to "Dance",
            "Club" to "Dance",
            "Eurodance" to "Dance",
            "Dubstep" to "Dance",
            "Drum & Bass" to "Dance",
            "Hard Dance" to "Dance",

            // Vocal
            "Vocal" to "Vocal",
            "A Cappella" to "Vocal",
            "Vocal Jazz" to "Vocal",
            "Vocal Pop" to "Vocal",
            "Choral" to "Vocal",
            "Barbershop" to "Vocal",
            "Traditional Vocal" to "Vocal",
    )

    @DrawableRes
    fun getGenreImage(genre: String): Int {
        val groupKey = genreToGroup[genre]
        return groupKey?.let { genreGroupImages[it] } ?: commonImage
    }
}