package app.simple.felicity.repository.models

import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

/**
 * Represents a playlist stored in the {@code playlists} table.
 *
 * <p>The {@code sortOrder} and {@code sortStyle} fields capture the user's last chosen
 * in-playlist sort configuration per playlist, mirroring the approach used by the Songs
 * and Favorites panels. A value of {@code -1} for {@code sortOrder} signals "use the
 * natural (manual) insertion order" so the playlist preserves the drag-and-drop sequence
 * the user arranged via the {@code position} column in {@link PlaylistSongCrossRef}.</p>
 *
 * <p>The {@code artworkPath} field holds an optional path to a user-selected cover image.
 * When {@code null} the UI should fall back to a mosaic of the first few songs' album art.</p>
 *
 * <p>When {@code isM3UPlaylist} is {@code true} the playlist was automatically created
 * by the library scanner from an M3U file found on the device. These playlists are
 * managed automatically — their contents are refreshed whenever the source file changes,
 * and they are removed when the M3U file is deleted. The {@code m3uFilePath} column
 * stores the absolute path to that source file so the scanner knows which file to
 * re-read on the next pass.</p>
 *
 * @author Hamza417
 */
@Parcelize
@Entity(tableName = "playlists")
data class Playlist(
        @PrimaryKey(autoGenerate = true)
        @ColumnInfo(name = "id")
        val id: Long = 0L,

        /** Human-readable display name of the playlist. */
        @ColumnInfo(name = "name")
        val name: String,

        /** Optional free-text description shown below the playlist name in the UI. */
        @ColumnInfo(name = "description")
        val description: String? = null,

        /** Epoch-millisecond timestamp when the playlist was first created. */
        @ColumnInfo(name = "date_created")
        val dateCreated: Long = System.currentTimeMillis(),

        /** Epoch-millisecond timestamp of the most recent structural change (rename, add/remove song, reorder). */
        @ColumnInfo(name = "date_modified")
        val dateModified: Long = System.currentTimeMillis(),

        /** Epoch-millisecond timestamp of the last time the playlist was opened or played. */
        @ColumnInfo(name = "last_accessed", defaultValue = "0")
        val lastAccessed: Long = 0L,

        /**
         * Optional absolute file-system path to a custom cover art image chosen by the user.
         * When {@code null} the UI falls back to a mosaic derived from the member songs' album art.
         */
        @ColumnInfo(name = "artwork_path")
        val artworkPath: String? = null,

        /**
         * The sort-field constant applied to songs inside this playlist.
         * Maps to a {@code BY_*} value from
         * {@link app.simple.felicity.constants.CommonPreferencesConstants}, or {@code -1} to
         * preserve the manual insertion order stored in
         * {@link PlaylistSongCrossRef#position}.
         */
        @ColumnInfo(name = "sort_order", defaultValue = "-1")
        val sortOrder: Int = -1,

        /**
         * Sort direction constant ({@code ASCENDING} or {@code DESCENDING}) from
         * {@link app.simple.felicity.constants.CommonPreferencesConstants}.
         * Only meaningful when {@code sortOrder} is not {@code -1}.
         */
        @ColumnInfo(name = "sort_style", defaultValue = "0")
        val sortStyle: Int = 0,

        /**
         * Whether the playlist should shuffle its tracks on playback.
         * Stored per-playlist so each playlist remembers its own shuffle preference.
         */
        @ColumnInfo(name = "is_shuffled", defaultValue = "0")
        val isShuffled: Boolean = false,

        /**
         * Whether this playlist is pinned to the top of the playlist list
         * regardless of the active list-level sort order.
         */
        @ColumnInfo(name = "is_pinned", defaultValue = "0")
        val isPinned: Boolean = false,

        /**
         * True when this playlist was automatically generated by the library scanner
         * from an M3U file discovered on storage. False for playlists the user created
         * manually inside the app. The UI can use this flag to visually distinguish the
         * two types — think of it as a little badge that says "I was born from a file!"
         */
        @ColumnInfo(name = "is_m3u_playlist", defaultValue = "0")
        val isM3UPlaylist: Boolean = false,

        /**
         * Absolute file-system path of the M3U file that this playlist was generated
         * from. Only set when {@code isM3UPlaylist} is {@code true}; null for all
         * regular user-created playlists. The scanner uses this path to detect file
         * changes and to clean up playlists whose source file has been deleted.
         */
        @ColumnInfo(name = "m3u_file_path")
        val m3uFilePath: String? = null
) : Parcelable

