name: Build APKs (Release)

on:
    workflow_dispatch:  # Allow manual triggering

jobs:
    build:
        name: Build Release APK
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Java and Android SDK
                uses: actions/setup-java@v4
                with:
                    java-version: '21' # Adjust the Java version as needed
                    distribution: 'temurin'

            -   name: Decode Keystore
                id: decode_keystore
                uses: timheuer/base64-to-file@v1
                with:
                    fileName: 'keystore/key.jks'
                    encodedString: ${{ secrets.SIGN_KEY }}

            -   name: Extract Version Name and Version Code
                run: |
                    # Extract versionName and versionCode from build.gradle
                    VERSION_NAME=$(cat music/build.gradle | grep -oP 'versionName "\K[^"]*')
                    VERSION_CODE=$(cat music/build.gradle | grep -oP 'versionCode \K\d+')

                    # Make the version name sentence case
                    # VERSION_NAME=$(echo "$VERSION_NAME" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')

                    echo "Version Name: $VERSION_NAME"
                    echo "Version Code: $VERSION_CODE"

                    # Set these values as environment variables for later steps
                    echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
                    echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

            -   name: Set Tag
                run: |
                    TAG=$(echo ${{ env.VERSION_NAME }} | tr '[:upper:]' '[:lower:]')
                    echo "TAG=${TAG}" >> $GITHUB_ENV
                    echo "Tag: ${TAG}" # Print tag to console

            -   name: Check Fastlane Changelogs
                run: |
                    if [ -f "fastlane/metadata/android/en-US/changelogs/${{ env.VERSION_CODE }}.txt" ]; then
                      echo "Changelog exists for version code ${{ env.VERSION_CODE }}."
                    else
                      echo "Changelog does not exist for version code ${{ env.VERSION_CODE }}."
                      exit 1
                    fi

            -   name: Accept Android SDK licenses
                run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

            -   name: Build Release APK
                run: |
                    chmod +x ./gradlew
                    ./gradlew clean assembleFossRelease --no-build-cache --rerun-tasks
                env:
                    SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                    SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

            -   name: Move APKs to Temporary Directory
                run: |
                    # Create a dedicated directory for the APKs
                    mkdir -p ${{ runner.temp }}/apks
                    
                    # Define the build flavour (adjust as needed)
                    FLAVOUR="foss"
                    
                    # Find all APKs and rename them to felicity_flavour_arch.apk
                    find music/ -name "*.apk" | while read -r apk; do
                        filename=$(basename "$apk")
                    
                        if [[ "$filename" == *"arm64-v8a"* ]]; then
                            new_filename="felicity_${FLAVOUR}_arm64-v8a.apk"
                        elif [[ "$filename" == *"armeabi-v7a"* ]]; then
                            new_filename="felicity_${FLAVOUR}_armeabi-v7a.apk"
                        elif [[ "$filename" == *"x86_64"* ]]; then
                            new_filename="felicity_${FLAVOUR}_x86_64.apk"
                        elif [[ "$filename" == *"x86"* ]]; then
                            new_filename="felicity_${FLAVOUR}_x86.apk"
                        elif [[ "$filename" == *"universal"* ]]; then
                            new_filename="felicity_${FLAVOUR}_universal.apk"
                        else
                            new_filename="felicity_${FLAVOUR}.apk"
                        fi
                    
                        echo "Moving $filename to $new_filename"
                        mv "$apk" "${{ runner.temp }}/apks/$new_filename"
                    done

            -   name: Create GitHub Release
                uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
                with:
                    files: |
                        ${{ runner.temp }}/apks/*.apk
                    name: ${{ env.VERSION_NAME }} # Use the original case for the release name
                    tag_name: ${{ env.TAG }} # Use lowercase for the tag
                    body_path: changelogs.md
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            ### Separate Upload Steps for Each Architecture Artifact ###

            -   name: Archive arm64-v8a APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-arm64-v8a
                    path: ${{ runner.temp }}/apks/*_arm64-v8a.apk
                    if-no-files-found: ignore

            -   name: Archive armeabi-v7a APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-armeabi-v7a
                    path: ${{ runner.temp }}/apks/*_armeabi-v7a.apk
                    if-no-files-found: ignore

            -   name: Archive x86_64 APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-x86_64
                    path: ${{ runner.temp }}/apks/*_x86_64.apk
                    if-no-files-found: ignore

            -   name: Archive x86 APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-x86
                    path: ${{ runner.temp }}/apks/*_x86.apk
                    if-no-files-found: ignore

            -   name: Archive Universal APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-universal
                    path: ${{ runner.temp }}/apks/*_universal.apk
                    if-no-files-found: ignore

            # Catch-all in case ABI splits aren't enabled and a standard non-arch APK is generated
            -   name: Archive Base APK
                uses: actions/upload-artifact@v4
                with:
                    name: felicity-base
                    path: |
                        ${{ runner.temp }}/apks/*.apk
                        !${{ runner.temp }}/apks/*_arm64-v8a.apk
                        !${{ runner.temp }}/apks/*_armeabi-v7a.apk
                        !${{ runner.temp }}/apks/*_x86.apk
                        !${{ runner.temp }}/apks/*_x86_64.apk
                        !${{ runner.temp }}/apks/*_universal.apk
                    if-no-files-found: ignore